# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Michael Broschinsky
tagline:             'A professional ePortfolio'
description:         'My careers in state government and higher education.'
url:                 http://michael.broschinsky.org
baseurl:             ''
# paginate:            5

# About/contact
author:
  name:              Michael Broschinsky
# Mark Otto uses url to point to his Twitter page.
  url:               https://twitter.com/mikebroschinsky
  email:             mikebroschinsky@gmail.com

# Custom vars
version:             1.0.0
